# Generated by Django 5.0 on 2024-01-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rescue_agency_admin', 'Rescue Agency Admin'), ('rescue_agency_team_leader', 'Team Leader'), ('rescue_agency_team_member', 'Team Member')], default='rescue_agency_team_member', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='rescueagency',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.role'),
        ),
    ]
