# Generated by Django 5.0 on 2024-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueagency',
            name='team_leaders_count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rescueagency',
            name='team_member_count',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
