# Generated by Django 5.0 on 2024-01-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescueagency',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='rescue_agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rescueagency'),
        ),
    ]
